### ISSUE TITLE
FS Project Review

### ISSUE THREAD

**Issue by HRemonen** [Marko-S-O/SimpleGymTracker#40]
This is a review for your fullstack-project. You do not need to implement possible suggestions for improvement mentioned here to receive your credits.

--- 

## User experience

- It's refreshing not to have to register an user actually
- Adding new workout is simple enough, I would love to have some UI element popping more though, now it feels like some of the elements get lost in the screen
- When adding sets the "+" and "-" controls do not do anything, visibly atleast. It seems like they really do add the value, but it doesn't show in the UI
- You can input negative values to the rep and weight fields, which shouldn't be - which leads to my point that pretty much all validation is missing, remember not to trust anything the user inputs and to validate everything
- I actually liked the program feature, very nice.
- Perhaps the navigation name "old prs" should just be old programs, I thought that it was for personal bests
- Maybe you should also add delete confirmations, now it's pretty easy to accidentally delete your set or exercise.
- The positioning of different UI elements is also kind of confusing, especially on the program page, maybe something to keep in mind in the future

## Code

- Good documentation! 
- Amazing that you've implemented android version also.
- Perhaps try to avoid using super generic database tablenames (such as data) because it doesn't help the readability. Better would be workouts or whatever.
- It would be benefitial to split the code by concerns, like by routes, data layer, and business logic. Makes the code easier to read, to add new logic, and to test
- In frontend code you are rendering hooks conditionally, which is violation of React. Such as in [Program.js file](https://github.com/Marko-S-O/SimpleGymTracker/blob/45cabd464e8cfe489b48e196cc016322df8b1545/gym-tracker-app/components/Program.js#L14-L19), [Workout.js](https://github.com/Marko-S-O/SimpleGymTracker/blob/45cabd464e8cfe489b48e196cc016322df8b1545/gym-tracker-app/components/Workout.js#L16-L36). Please refer to the [rules of hooks](https://react.dev/reference/rules/rules-of-hooks) for a full guide
- Perhaps a little nitpicking, but why is there a UIconstants.js and setConstants.js files in components directory and not utils or something more suiting
- Codebase could use prettier for universal formatting, now it's somewhat all over the place which style you follow. Also eslint configured properly would help with errors
- There are two dataHelper.js files I wonder why, again the naming of things is important

## Conclusion

Nice project. I would go the extra steps to ensure that the data is validated and that everything is working as it should. Also pay attention to the naming conventions you are using, you want to name things based on what they really are or do. I HOPE that you will fix the conditional hook rendering. You will get your credits in the near future.

**Comment by Marko-S-O** [comment]
Hei Henri,

Kiitos hyödyllisistä palautteista! Osasta on jo issue parannuslistalla, tuo
Reactin hookien käyttö on varmasti tarpeellinen pointti, joka pitää
fiksata, ja joitain käyttöliittymäjuttuja parantelen ketterässä hengessä
kokemuksen perusteella sitten. Harmittavasti onnistuin juuri
automaattisella käännösskriptillä eilen viemään fly.io:hon version, jossa
tuo numeroiden syöttökomponentti oli buginen, mutta se ei liene pihvi tässä
kohden.

Mukavaa talvea!
t. Marko

ti 26.11.2024 klo 17.08 Henri Remonen ***@***.***) kirjoitti:
